name: Process ESA NEOCC data
run-name: Process latest close flyby data from ESA NEOCC
on:
  schedule:
    - cron: '11 1 * * *'
  workflow_dispatch:
jobs:
  process-esa-data:
    runs-on: ubuntu-latest
    environment: Test
    steps:
    - uses: actions/checkout@v3
      with:
        token: ${{ secrets.WORKFLOW_GIT_ACCESS_TOKEN }}
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install httpx sgp4 astropy numpy matplotlib poliastro spacetrack
    - name: Run main process
      env: 
        SPACETRACK_USER: ${{ secrets.SPACETRACK_USER }}
        SPACETRACK_PASSWD: ${{ secrets.SPACETRACK_PASSWD }}
      run: |
        cd src
        python conjunction_sat_asteroid.py
    - name: GIT commit and push all new and changed files
      env: 
        CI_COMMIT_MESSAGE: Daily update
        CI_COMMIT_AUTHOR: Action Script
      run: |
        git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        git config --global user.email "rtolesnikov@yahoo.com"
        git add -A
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
