name: Process ESA NEOCC data
run-name: Process latest close flyby data from ESA NEOCC
on:
  schedule:
    - cron: '11 1 * * *'
  workflow_dispatch:
jobs:
  process-esa-data:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v3
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install httpx sgp4 astropy numpy matplotlib poliastro
    - name: Run main process
      run: |
        cd src
        python conjunction_sat_asteroid.py
    - name: GIT commit and push all changed files
      env: 
        CI_COMMIT_MESSAGE: Daily update
        CI_COMMIT_AUTHOR: Action Script
      run: |
        #git config --global user.name "${{ env.CI_COMMIT_AUTHOR }}"
        #git config --global user.email "username@users.noreply.github.com"
        git commit -a -m "${{ env.CI_COMMIT_MESSAGE }}"
        git push
